### PR TITLE
Honeybadger appender missing context/request

### PR DESCRIPTION
**Pull request by npepinpe**
When using Honeybadger (only tested with 2.0) in a Rails app, the Rack request is automatically submitted along with the exception.

When using SemanticLogger, this is missing from the reports, even on normal uncaught exceptions (i.e. not through a direct Logger.error call).

Further, anything set in Honeybadger.context is also not passed on to Honeybadger, only the context provided by the log call.

I suspect this is due to thread local variables. As far as I can tell, Honeybadger sets the context (and clears it after every Rack request) through Thread local variables (`Thread.current[:__honeybadger_request]` and `Thread.current[:__honeybadger_context]`), which might explain why they are missing by the time we get into the appender thread.

Edit: I confirmed this by passing along those two variables to the appender thread local variables from a controller action. The request needs to be added to the context under the key request, but otherwise it seems work as expected.

``` ruby
class MyController < ActionController:Base
def trigger_error
  thread = SemanticLogger::Logger.class_variable_get(:@@appender_thread)
  thread[:__honeybadger_request] = Thread.current[:__honeybadger_request]
  thread[:__honeybadger_context] = Honeybadger.get_context
  raise StandardError, 'Testing'
end
```

Then in the appender merging everything. I'm not sure what would be the ideal approach here.

See: 
- [Honeybadget.get_context](https://github.com/honeybadger-io/honeybadger-ruby/blob/a0da4c03c3833fcf87ce48789736b496550067e7/lib/honeybadger.rb#L185)
- [Honeybadger.with_request](https://github.com/honeybadger-io/honeybadger-ruby/blob/583298ed182c8260116982ee5eeed7a1c0f011f1/lib/honeybadger/config.rb#L198)

### CODE REVIEW

**Comment by npepinpe** [comment]
See pull request, I think the solution with the formatter is cleaner, although I don't like looking up the caller thread by name.

Ideally, there would be a way to transfer select thread local variables from the caller thread to the appender, depending on which appenders are in use. Honeybadger uses __honeybadger_request, Sidekiq uses sidekiq_context, etc.

This could be part of the Log struct, and would solve the issue of finding the context of a dead thread (not possible at the moment in this PR).

**Comment by npepinpe** [comment]
I think the Thread.find_by_name method might lead to race conditions with JRuby, where Thread.list returns a thread, but we are unable to retrieve the native thread as it already went away.

The cleanest way would be to directly have a reference to the caller thread in the Log struct, or to have each Appender be able to request additional thread local context that would be passed on with every log call.

**Comment by npepinpe** [comment]
After much thought, and a code review from a team member, I realised looking up the previous thread local variables during an appending operation can lead to concurrency issue if the logging queue was backed.

I added a thread_context portion to the Log struct, and appenders can now define specific keys they need from the logging thread. In Logger#log, the context is read and added to the struct, so that the appending thread has the value that was present at log time.

I realise it is still vulnerable to a concurrency issue, primarily since those objects are not frozen, but I figured duplicating them could lead to memory growth issues. I'm open to discussion anyway.

I also rewrote the Honeybadger integration in general, and it now plays nicer with the Honeybadger front-end.

**Comment by reidmorrison** [comment]
A better approach would be for Semantic Logger to supply a `before_log` callback that any appender could hook into to capture custom contextual information. That way it does not need to know about thread variables etc.

Definitely have to `dup` the thread local variables otherwise they can change before logged since it is logged in a separate thread.

Using the `before_log` callback it can call `Honeybadger.get_context.dup` and put that in a custom field in the log struct. Which avoids accessing the private honeybadger thread local variables directly.

Additionally the callback could decide to only capture the honey badger context when above for example warn log levels, or if an exception is included to prevent any impact on performance.

**Comment by npepinpe** [comment]
Sounds good.

I feel calling `dup` gives a false sense of security, as for most complex objects (or any collection) it would be a shallow copy, but if it might help catch some cases, it's better than nothing.

**Comment by reidmorrison** [comment]
The ability to capture context in the original application thread before passing it onto the logging thread has now been added in master:

From the appender add the following code to register the subscriber that is called every time a logging call is made:

~~~ruby
SemanticLogger.on_log do |log|
  log.set_context(:honeybadger, Honeybadger.get_context)
end
~~~

This option is more performant on JRuby:

~~~ruby
module CaptureContext
  def call(log)
    log.set_context(:honeybadger, Honeybadger.get_context)
  end
end
SemanticLogger.on_log(CaptureContext)
~~~

Give it a try and let me know if this will allow the honey badger appender to capture application context.

**Comment by reidmorrison** [comment]
It looks like the latest community submitted PR's seem address this need.

**Pull request closed without merging**
