### PR TITLE
Prepend slash(/) character in every HTTP request to ElasticSearch API

### PR DESCRIPTION
**Pull request by fidelisrafael**
Hi guys!

I'm trying to integrate `semantic_logger` with my ElasticSearch cluster. I tried to send structured log data over the REST API of ES....
For some reason without the `/(slash)` in the begging of `request URI` I **always** receives a `400 Bad Request` response...this drove me crazy....
Cause when I pointed the `appender url` to my local machine(`http://localhost:9200` - "not proxyed"), everything works, but when I try to use a remote ElasticSearch REST API through a `nginx reverse proxy` the request is dropped.

This is the response in my log:

```
[31mSemanticLogger[0m -- Bad HTTP response from: http://[hidden]]/ code: 400, <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.10.0 (Ubuntu)</center>
</body>
</html>
```
So adding the slash makes everything works...I don't have that time now to really undestand whats is happening, but looks that nginx cant route the request properly without the slash...

As you can see in nginx logs:

#### without slash - 400
```
MYIP - - [07/Nov/2016:01:38:53 +0000] "POST rails-docomercioapi-application-2016.11.07/application-logs HTTP/1.1" 400 182 "-" "-"
```

#### with slash - 201

```
MYIP - trackmob [07/Nov/2016:01:44:29 +0000] "POST /rails-docomercioapi-application-2016.11.07/application-logs HTTP/1.1" 201 194 "-" "Ruby"
```

I only changed the way request uri is formatted to `ElasticSearch`, I don't think that is a good way doing this global...so I kept others appenders intouched.

Note: This error **ONLY** happens when I try to send a request through a `Net::HTTP#request`, everything is fine when I use `curl`, for example.

### CODE REVIEW

**Comment by reidmorrison** [comment]
I just tried again using the latest versions of Elastic Search v5.1.1, Kibana v5.1.1, and Semantic Logger v4.0.0.beta1. Cannot reproduce any issues with this combination.

My config is as follows:
~~~ruby
SemanticLogger.add_appender(
  appender: :elasticsearch,
  url:      'http://localhost:9200'
)
~~~

What version of elastic search, ruby and semantic logger are you using?

**Comment by reidmorrison** [comment]
Thank you for letting me know about the HTTP empty path.

After much research and refactoring I added the change to the v4 branch: https://github.com/rocketjob/semantic_logger/commit/3a941232294c17e0cde929de0222e4c9bb3ec54b

**Comment by fidelisrafael** [comment]
Cool! So we can close this?

**Comment by reidmorrison** [comment]
Thank you for the feedback.

**Pull request closed without merging**
